# Generated by Django 4.2.7 on 2026-04-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appfeature'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='core_invtrans_product_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_created_929486_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_status_6fe5d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='core_order_payment_6639e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='core_orderitem_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='core_orderitem_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_product_archived_avail_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_product_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_product_best_seller_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_product_new_arrival_idx',
        ),
    ]
