# Generated by Django 4.2.7 on 2026-04-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_inventorytransaction_core_invtrans_product_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk-in'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], default='walk_in', max_length=10),
        ),
    ]
